name: WAS

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
    
      - name: make application.yml
        run: |
          cd ./src/main/resources
        
          # application.yml 파일 생성
          touch ./application.yml
          touch ./key.yml
        
          # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.WAS_APPLICATION }}" >> ./application.yml
          echo "${{ secrets.WAS_KEY }}" >> ./key.yml
        
        shell: bash

      - name: Build with Gradle
        run: |
          ./gradlew build -x check

      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.WAS_DOCKER_USERNAME }} -p ${{ secrets.WAS_DOCKER_PASSWORD }}
          docker build -t ${{ secrets.WAS_DOCKER_USERNAME }}/${{ secrets.WAS_DOCKER_REPO }} .
          docker push ${{ secrets.WAS_DOCKER_USERNAME }}/${{ secrets.WAS_DOCKER_REPO }} 

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ubuntu
          key: ${{ secrets.WAS_PEM_KEY }}
          port: 22
          script: |
            sudo docker kill ${{ secrets.WAS_DOCKER_REPO }}
            sudo docker container prune -f
            sudo docker pull ${{ secrets.WAS_DOCKER_USERNAME }}/${{ secrets.WAS_DOCKER_REPO }}
            sudo docker run -d -p 8080:8080 --name ${{ secrets.WAS_DOCKER_REPO }} ${{ secrets.WAS_DOCKER_USERNAME }}/${{ secrets.WAS_DOCKER_REPO }}
            sudo docker image prune -f
